[mypy]
python_version = 3.10
strict = True
files = src, tests
disallow_untyped_defs = True
warn_return_any = True
no_implicit_optional = True

[mypy-agentplatform.*]
ignore_missing_imports = True

[mypy-google.api_core.*]
ignore_missing_imports = True

[mypy-playwright.*]
ignore_missing_imports = True
